// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEEdDsDgXOQlbWAhV8vXS-R6zVxcLrta8',
    appId: '1:863927220020:web:27eb522ff27689ce5d1761',
    messagingSenderId: '863927220020',
    projectId: 'university-a4030',
    authDomain: 'university-a4030.firebaseapp.com',
    storageBucket: 'university-a4030.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDysbRGr7TaMqEb8z5ecki7WT-MlGXDMg',
    appId: '1:863927220020:android:d55cf3176ef5e99e5d1761',
    messagingSenderId: '863927220020',
    projectId: 'university-a4030',
    storageBucket: 'university-a4030.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5x0Pu8L_Wd7z06HK8X9fSMO0umbAOSBI',
    appId: '1:863927220020:ios:165c9381d3b387ac5d1761',
    messagingSenderId: '863927220020',
    projectId: 'university-a4030',
    storageBucket: 'university-a4030.appspot.com',
    iosBundleId: 'com.example.uorFindManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5x0Pu8L_Wd7z06HK8X9fSMO0umbAOSBI',
    appId: '1:863927220020:ios:165c9381d3b387ac5d1761',
    messagingSenderId: '863927220020',
    projectId: 'university-a4030',
    storageBucket: 'university-a4030.appspot.com',
    iosBundleId: 'com.example.uorFindManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEEdDsDgXOQlbWAhV8vXS-R6zVxcLrta8',
    appId: '1:863927220020:web:bf097d1b15b33a3b5d1761',
    messagingSenderId: '863927220020',
    projectId: 'university-a4030',
    authDomain: 'university-a4030.firebaseapp.com',
    storageBucket: 'university-a4030.appspot.com',
  );
}
